- LICENSE
> fix: it's 2024 4Head

- README.md
Updates the hyperlink in the README which points to the license (caused by #1)
> Update hyperlink to license in README

- .github/workflows/build.yml
- Cargo.lock
- Cargo.toml
- apps/event-api/Cargo.toml
- apps/event-api/Dockerfile
- apps/event-api/src/config.rs
- apps/event-api/src/health.rs
- apps/event-api/src/http/mod.rs
- apps/event-api/src/http/v3/mod.rs
- apps/event-api/src/metrics/mod.rs
- apps/event-api/src/utils.rs
Add CI Builds for the event-api
> Add CI Builds

- database/automod.sql
- database/badges.sql
- database/calculate_entitlements.py
- database/emotes.sql
- database/files.sql
- database/global.sql
- database/pages.sql
- database/paints.sql
- database/product.sql
- database/roles.sql
- database/ticket.sql
- database/users.sql
Adds the initial database design for 7TV
API-8
> Database Design

- .gitignore
- website/src/components/nav/search-bar.svelte
- website/src/components/nav/top-nav.svelte
- website/src/components/paint-preview.svelte
- website/src/components/select.svelte
- website/src/components/store/banner.svelte
- website/src/components/store/monthly-paints.svelte
- website/src/routes/emotes/+layout.svelte
- website/src/routes/store/+page.svelte
- website/src/routes/store/merch/+page.svelte
- website/src/routes/store/paint-bundles/+page.svelte
- website/src/styles/global.scss
Implement store paint bundles page.
WEB-31
> feat: store paint bundles mock

- CONTRIBUTING.md
- website/README.md
I found some broken links and a typo while reading through the README and contributing guidelines.
> Two broken links and a typo

- website/CONTRIBUTING.md
- website/README.md
Add some guidelines for code style.
WEB-62
> docs(website): add contribution guidelines

- website/src/components/checkbox.svelte
- website/src/components/dialogs/cart-dialog.svelte
- website/src/components/dialogs/dialog.svelte
- website/src/components/dialogs/upload-dialog.svelte
- website/src/components/nav/menu.svelte
- website/src/components/nav/top-nav.svelte
- website/src/lib/utils.ts
- website/src/routes/sign-in/+page.svelte
- website/src/routes/store/paint-bundles/+page.svelte
- website/src/styles/variables.scss
Implements cart dialog mock.
WEB-71
> feat(website): cart dialog mock

- website/src/components/checkbox.svelte
- website/src/components/settings/user-table.svelte
- website/src/components/toggle.svelte
- website/src/routes/emote-sets/[id]/+page.svelte
- website/src/routes/settings/notifications/+page.svelte
Implement notification settings mock.
WEB-43
> feat(website): notification settings mock

- website/src/routes/settings/+layout.svelte
- website/src/routes/settings/blocked/+page.svelte
- website/src/routes/settings/blocking/+page.svelte
Implement blocked settings mock.
WEB-45
> feat(website): blocked settings mock

- website/package.json
- website/pnpm-lock.yaml
- website/src/components/checkbox.svelte
- website/src/components/flags.svelte
- website/src/components/icons/payment-brand.svelte
- website/src/components/settings/billing-table.svelte
- website/src/components/settings/editors.svelte
- website/src/components/settings/payment-method.svelte
- website/src/components/settings/user-table.svelte
- website/src/components/store/faq.svelte
- website/src/components/store/your-sub.svelte
- website/src/components/sub-info.svelte
- website/src/components/tab-link.svelte
- website/src/components/toggle.svelte
- website/src/routes/+layout.svelte
- website/src/routes/discover/+layout.svelte
- website/src/routes/emotes/(directory)/+layout.svelte
- website/src/routes/settings/+layout.svelte
- website/src/routes/settings/billing/+page.svelte
- website/src/routes/settings/blocked/+page.svelte
- website/src/routes/settings/notifications/+page.svelte
Implement billing settings mock.
WEB-47
> feat(website): billing settings mock

- website/src/components/checkbox.svelte
- website/src/components/dialogs/cart-dialog.svelte
- website/src/components/dialogs/delete-account-dialog.svelte
- website/src/components/dialogs/upload-dialog.svelte
- website/src/routes/settings/+page.svelte
Implement account deletion modal mock.
WEB-84
> feat(website): account deletion modal mock

- website/src/components/checkbox.svelte
- website/src/components/dialogs/add-emote-dialog.svelte
- website/src/components/dialogs/delete-account-dialog.svelte
- website/src/components/expandable.svelte
- website/src/components/flags.svelte
- website/src/routes/emotes/[id]/+layout.svelte
- website/src/routes/settings/+page.svelte
Implement add emote dialog mock.
WEB-85
> feat(website): add emote dialog mock

- website/src/components/checkbox.svelte
- website/src/components/dialogs/add-emote-dialog.svelte
- website/src/components/dialogs/cart-dialog.svelte
- website/src/components/dialogs/delete-account-dialog.svelte
- website/src/components/dialogs/delete-emote-dialog.svelte
- website/src/components/dialogs/dialog.svelte
- website/src/components/dialogs/edit-emote-dialog.svelte
- website/src/components/dialogs/emote-dialog.svelte
- website/src/components/dialogs/report-emote-dialog.svelte
- website/src/components/dialogs/transfer-emote-dialog.svelte
- website/src/components/input/text-input.svelte
- website/src/routes/emotes/[id]/+layout.svelte
- website/src/styles/global.scss
Implement transfer, delete and report emote dialog mocks.
WEB-95, WEB-89, WEB-93
> feat(website): emote dialog mocks

- website/src/components/dialogs/edit-emote-set-dialog.svelte
- website/src/components/dialogs/remove-emotes-dialog.svelte
- website/src/lib/stores.ts
- website/src/routes/+layout.svelte
- website/src/routes/emotes/(directory)/(emotes)/+layout.svelte
- website/src/routes/emotes/(directory)/bookmarked/+layout.svelte
- website/src/routes/emotes/(directory)/bookmarked/+page.svelte
- website/src/routes/emotes/(directory)/bookmarked/emotes/+page.ts
- website/src/routes/emotes/(directory)/bookmarked/sets/+page.svelte
- website/src/routes/emotes/(directory)/bookmarked/users/+page.svelte
Implement bookmarked page mock.
WEB-107
> feat(website): bookmarked mock

- website/src/components/dialogs/add-emote-dialog.svelte
- website/src/components/dialogs/cart-dialog.svelte
- website/src/components/dialogs/delete-account-dialog.svelte
- website/src/components/dialogs/delete-emote-dialog.svelte
- website/src/components/dialogs/delete-emote-set-dialog.svelte
- website/src/components/dialogs/edit-emote-dialog.svelte
- website/src/components/dialogs/edit-emote-set-dialog.svelte
- website/src/components/dialogs/emote-dialog.svelte
- website/src/components/dialogs/remove-emotes-dialog.svelte
- website/src/components/dialogs/report-emote-dialog.svelte
- website/src/components/dialogs/transfer-emote-dialog.svelte
- website/src/components/dialogs/upload-dialog.svelte
- website/src/components/input/button.svelte
- website/src/components/input/menu-button.svelte
- website/src/components/nav/menu.svelte
- website/src/routes/emotes/[id]/+layout.svelte
- Refactor to use form elements when appropriate.
- Extract menu buttons into common component.
WEB-104
> refactor(website): use form elements where appropriate

- website/src/components/emote-preview.svelte
- website/src/components/emote-set-preview.svelte
- website/src/components/flags.svelte
- website/src/components/input/menu-button.svelte
- website/src/routes/emotes/(directory)/(emotes)/+page.svelte
- website/src/routes/emotes/[id]/+layout.svelte
This pull request adds new styling for flags.
WEB-103
> feat(website): new flags styling

- website/src/components/cms-page-preview.svelte
- website/src/components/drop-down.svelte
- website/src/routes/[cms_slug]/+page.svelte
- website/src/routes/[cms_slug]/+page.ts
- website/src/routes/discover/+page.svelte
This pr implements the news page mock.
WEB-22
> feat(website): news page mock

- apps/api/src/database/mod.rs
- apps/api/src/database/ticket.rs
- database/tickets.sql
> feat(api): model tickets

- shared/src/database/types/automod.rs
- shared/src/database/types/file.rs
- shared/src/database/types/page.rs
- shared/src/database/types/product/code.rs
- shared/src/database/types/product/mod.rs
- shared/src/database/types/product/purchase.rs
- shared/src/database/types/ticket.rs
- shared/src/database/types/user/connection.rs
- shared/src/database/types/user/editor.rs
- shared/src/database/types/user/gift.rs
- shared/src/database/types/user/product.rs
- shared/src/database/types/user/relation.rs
> fix(api): clean up database types

- apps/api/src/http/v3/gql/mutations/bans.rs
- apps/api/src/http/v3/gql/mutations/emote_sets.rs
- apps/api/src/http/v3/gql/mutations/emotes.rs
- apps/api/src/http/v3/gql/mutations/reports.rs
- apps/api/src/http/v3/gql/mutations/roles.rs
- apps/api/src/http/v3/gql/mutations/users.rs
- apps/api/src/http/v3/gql/queries/audit_log.rs
- apps/api/src/http/v3/gql/queries/role.rs
- apps/api/src/http/v3/gql/queries/user/mod.rs
- apps/api/src/http/v3/rest/auth/login.rs
- apps/api/src/http/v3/rest/auth/mod.rs
- apps/api/src/http/v3/rest/emotes.rs
- apps/api/src/image_processor_callback.rs
- apps/data-brittler/src/config.rs
- apps/data-brittler/src/download_cosmetics.rs
- apps/data-brittler/src/jobs/audit_logs.rs
- apps/data-brittler/src/jobs/emote_sets.rs
- apps/data-brittler/src/jobs/entitlements.rs
- apps/data-brittler/src/jobs/prices.rs
- apps/data-brittler/src/jobs/system.rs
- apps/data-brittler/src/main.rs
- apps/data-brittler/src/types/audit_log.rs
- shared/src/database/types/audit_log.rs
- shared/src/database/types/role/permissions.rs
Manually inserts audit logs from API endpoints.
> feat(api): create audit logs

- apps/cdn/src/cache/mod.rs
> fix(cdn): s3 error logging

- Cargo.lock
- Cargo.toml
- apps/api/Cargo.toml
- apps/cdn/CC_APACHE2_LICENSE
- apps/cdn/Cargo.toml
- apps/cdn/Dockerfile
- apps/cdn/src/cache/mod.rs
- apps/cdn/src/config.rs
- apps/cdn/src/http/cdn.rs
- apps/cdn/src/http/mod.rs
- apps/cdn/src/main.rs
- apps/cdn/src/metrics.rs
- apps/data-brittler/Cargo.toml
- apps/event-api/Cargo.toml
- apps/tmp/Cargo.toml
- apps/tmp/src/main.rs
- shared/Cargo.toml
> minor fixes for cdn

- Cargo.lock
- apps/cdn/Cargo.toml
- apps/cdn/src/cache/mod.rs
- apps/cdn/src/config.rs
- apps/cdn/src/http/mod.rs
- apps/cdn/src/http/ratelimit.rs
- apps/cdn/src/metrics.rs
Implement a limit per IP range to protect against DOS/DDOS attacks by opening large number of TCP connections.
This does not add a limit to the number of requests that actors can do per second, that is still uncapped however the limit is for how many unique connections they can open.
If we notice abuse on RPS based attacks then we can impose a limit to the RPS per open connection.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about …
> feat(cdn): implement ip range limits

- Cargo.lock
- apps/api/Cargo.toml
- apps/api/src/config.rs
- apps/api/src/http/v3/gql/mutations/bans.rs
- apps/api/src/http/v3/gql/mutations/cosmetics.rs
- apps/api/src/http/v3/gql/mutations/emote_sets/mod.rs
- apps/api/src/http/v3/gql/mutations/emotes.rs
- apps/api/src/http/v3/gql/mutations/reports.rs
- apps/api/src/http/v3/gql/mutations/roles.rs
- apps/api/src/http/v3/gql/queries/emote.rs
- apps/api/src/http/v3/gql/queries/user/mod.rs
- apps/api/src/http/v3/mod.rs
- apps/api/src/http/v3/rest/auth/login.rs
- apps/api/src/http/v3/rest/emotes.rs
- apps/api/src/http/v3/validators.rs
- Validate gql input
- Fix login endpoint
> feat(api): gql input validators and login fix

- Cargo.lock
- apps/api/Cargo.toml
- apps/api/src/config.rs
- apps/api/src/global.rs
- apps/api/src/http/egvault/cancel.rs
- apps/api/src/http/egvault/mod.rs
- apps/api/src/http/egvault/payment_method.rs
- apps/api/src/http/egvault/redeem.rs
- apps/api/src/http/egvault/subscribe.rs
- apps/api/src/http/internal/rest/webhooks/paypal/mod.rs
- apps/api/src/http/internal/rest/webhooks/paypal/sale.rs
- apps/api/src/http/internal/rest/webhooks/stripe/charge.rs
- apps/api/src/http/internal/rest/webhooks/stripe/checkout_session.rs
- apps/api/src/http/internal/rest/webhooks/stripe/invoice.rs
- apps/api/src/http/internal/rest/webhooks/stripe/mod.rs
- apps/api/src/http/internal/rest/webhooks/stripe/price.rs
- apps/api/src/http/v3/gql/queries/message.rs
- apps/api/src/main.rs
- apps/api/src/stripe_client.rs
- apps/data-brittler/src/types/message.rs
- shared/Cargo.toml
> feat: improve stripe integration

- Cargo.lock
- apps/data-brittler/src/jobs/users.rs
- clickhouse/emote_stats.sql
> fix(data-brittler): user job

- apps/cdn/src/cache/mod.rs
- apps/cdn/src/http/cdn.rs
> feat(cdn): new cdn

- apps/api/src/http/v3/gql/mutations/users.rs
> fix(api): prevent user from removing last connection

- apps/api/src/transactions.rs
> fix(api): transaction error

- apps/api/src/http/egvault/mod.rs
- apps/api/src/http/internal/rest/webhooks/paypal/sale.rs
- apps/api/src/sub_refresh_job.rs
- shared/src/database/types/product/subscription.rs
- shared/src/database/types/user/mod.rs
> fix(api): paypal subs

- apps/api/src/http/v4/gql/types/event/user.rs
- apps/website/src/components/dialogs/add-emote-dialog.svelte
- apps/website/src/components/users/user-event.svelte
- apps/website/src/lib/setMutations.ts
- apps/website/src/routes/users/[id]/+page.svelte
- apps/website/src/routes/users/[id]/activity/+page.svelte
- apps/website/src/routes/users/[id]/emote-sets/+page.ts
- apps/website/src/routes/users/[id]/uploaded/+page.svelte
> fix: v4 user events

- apps/api/src/http/v4/rest/auth/mod.rs
- apps/website/src/components/dialogs/sign-in-dialog.svelte
- apps/website/src/routes/login/+page.svelte
- apps/website/src/routes/login/callback/+page.svelte
- apps/website/src/routes/login/callback/+page.ts
> fix(api): v4 login

- apps/api/src/http/v3/gql/mutations/emote_sets/emote_add.rs
- apps/api/src/http/v3/gql/mutations/emote_sets/mod.rs
- apps/api/src/http/v4/gql/mutations/emote_set/operation.rs
Fix emote set tx and capacity check
Closes #155 
> fix(api): emote set tx and capacity check

- apps/api/build.rs
- apps/api/src/http/mod.rs
- apps/api/src/http/v4/gql/types/user/mod.rs
- apps/website/schema.graphql
- apps/website/src/components/emotes/tags.svelte
- apps/website/src/components/flags.svelte
- apps/website/src/routes/users/[id]/+layout.svelte
- apps/website/src/routes/users/[id]/+layout.ts
- apps/website/src/routes/users/[id]/cosmetics/+page.svelte
- apps/website/src/routes/users/[id]/emote-sets/+page.ts
- apps/website/src/styles/variables.scss
Show special sets again and some other fixes
> fix: show special sets again and some other fixes

- apps/website/src/locales/en.json
Fixes a small typo in the Store page.
> fix(website): typo

- apps/api/src/http/v4/gql/types/event/user.rs
- apps/api/src/http/v4/gql/types/user/billing.rs
- apps/website/src/components/dialogs/delete-emote-set-dialog.svelte
- apps/website/src/components/emotes/emote-info.svelte
- apps/website/src/components/responsive-image.svelte
- apps/website/src/lib/userMutations.ts
- apps/website/src/lib/utils.ts
> fix(website): apple trolling

- apps/website/src/components/input/text-input.svelte
- apps/website/src/components/nav/global-search.svelte
- apps/website/src/components/settings/editors.svelte
- apps/website/src/lib/layout.ts
- apps/website/src/routes/+layout.svelte
- apps/website/src/routes/emotes/(directory)/(emotes)/+layout.svelte
I changed the padding and gaps of the nav elements that handle sorting. I also fixed an issue with text inputs being pushed down.
I also added a button to hide the "Under construction" bar that appears on the new website, and moved the bar itself under the global horizontal navbar.
Another thing I added is that the page where you manage your editors shows "No editors" when you have no editors or if you aren't an editor for any channels.
> Website improvements

- apps/website/src/lib/layout.ts
- apps/website/src/routes/+layout.svelte
- apps/website/src/routes/extension/auth/+page.svelte
Extension auth page and some small fixes
> feat: extension auth

- apps/api/src/http/v4/gql/mutations/user_editor/mod.rs
- apps/api/src/http/v4/gql/mutations/user_editor/operation.rs
- apps/website/schema.graphql
- apps/website/src/components/dialogs/active-emote-set-dialog.svelte
- apps/website/src/components/dialogs/edit-emote-set-dialog.svelte
- apps/website/src/components/error.svelte
- apps/website/src/components/events/emote-set-event.svelte
- apps/website/src/components/flags.svelte
- apps/website/src/components/input/range.svelte
- apps/website/src/components/input/tags-input.svelte
- apps/website/src/components/settings/connections-setting.svelte
- apps/website/src/components/settings/editors.svelte
- apps/website/src/components/settings/main-connection-select.svelte
- apps/website/src/components/settings/profile-picture-setting.svelte
- apps/website/src/components/store/benefits.svelte
- apps/website/src/lib/auth.ts
- apps/website/src/lib/userMutations.ts
- apps/website/src/routes/+error.svelte
- apps/website/src/routes/emote-sets/[id]/+page.svelte
- apps/website/src/routes/settings/+page.svelte
- apps/website/src/routes/settings/editors/+page.svelte
- apps/website/src/routes/settings/editors/editing-for/+page.svelte
- apps/website/src/routes/users/[id]/+layout.svelte
- apps/website/src/routes/users/[id]/+layout.ts
- apps/website/src/routes/users/[id]/cosmetics/+page.svelte
- shared/src/database/types/user/editor.rs
Some fixes and missing features
> fix: hotfixes

- apps/api/src/image_processor/profile_picture.rs
> fix(api): stale profile pictures

- apps/website/src/components/emotes/tags.svelte
- apps/website/src/components/flags.svelte
- apps/website/src/components/input/text-input.svelte
- apps/website/src/components/nav/global-search.svelte
- apps/website/src/lib/auth.ts
- apps/website/src/lib/emoteMutations.ts
- apps/website/src/lib/emoteQuery.ts
- apps/website/src/routes/emote-sets/[id]/+page.svelte
- apps/website/src/routes/emote-sets/[id]/+page.ts
- apps/website/src/routes/settings/+page.svelte
- apps/website/src/routes/users/[id]/+page.svelte
- apps/website/src/routes/users/[id]/uploaded/+page.svelte
Completes emote set page
Closes #187 
> feat(website): emote set page + fixes

- docs/website.md
> docs: add website docs

- apps/api/src/connections/discord.rs
Use username instead of display name when linking/logging in to discord
> api: use discord username

- apps/api/src/http/internal/rest/webhooks/stripe/invoice.rs
- apps/api/src/sub_refresh_job.rs
Add Valentine Event
Fix error caused when trying to cancel paypal subscription that has already been canceled
> Valentine Event

- apps/website/pnpm-lock.yaml
- apps/website/src/app.d.ts
- apps/website/src/app.html
- apps/website/src/components/google-analytics.svelte
- apps/website/src/routes/+layout.svelte
- apps/website/src/routes/event/+page.svelte
move google analytics to module
> Move google analytics to module

- Cargo.lock
- apps/api/Cargo.toml
- apps/api/src/config.rs
- apps/api/src/connections/kick.rs
- apps/api/src/connections/mod.rs
- apps/api/src/http/v3/rest/auth/login.rs
- apps/api/src/http/v3/rest/auth/mod.rs
- apps/api/src/http/v4/rest/auth.rs
- apps/website/src/components/dialogs/sign-in-dialog.svelte
- apps/website/src/components/settings/connections-setting.svelte
Implements OAuth 2.1
Adds kick as a login option on the website
> Login with KICK
